version: "3"

services:
  poll:
    build: ./poll
    networks:
      - poll-tier
    ports:
      - "5000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  redis:
    image: redis:latest
    networks:
      - poll-tier
      - back-tier
    expose:
      - "6379"
    restart: always

  worker:
    build: ./worker
    networks:
      - back-tier
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always

  db:
    image: postgres:latest
    networks:
      - result-tier
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always

  result:
    build: ./result
    networks:
      - result-tier
    ports:
      - "5001:80"
    depends_on:
      - worker
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
